### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by jrah** [jrah/vue-wecraft#1]
# WeCraft

## Overview
Create basic MVP website. 

### Introduction
- [ ] Familiarise with nuxtconfig.js
- [ ] Familiarise with TailwindCSS and SCSS
- [ ] Familiarise with components and props
- [ ] Familiarise with looping through JSON

### Work
Complete landing page as in the sketch (landing page and process only). There are eight unique components. 

### Notes
- Use `flexbox` for layout (see Tailwind for reference)
- Feel free to add unsplash images as placeholders
- Brand colour is #19A974

`default.vue`
```scss
@import '~assets/scss/mixins';
html {
  @apply font-sans font-normal text-black leading-normal;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  @apply font-raleway;
}

p,
blockquote,
nav,
button,
a {
  @apply font-roboto;
}

.container {
  @apply px-8;
  @include mq(ns) {
    @apply px-16;
  }
  @extend %mwc;
}
.site-canvas {
  @apply bg-white;
  transition: 0.3s ease transform;
  position: relative;
  overflow: hidden;
}

.link {
  @include mq(ns) {
    &:after {
      content: '';
      @apply bg-navy;
      position: absolute;
      left: 0;
      bottom: -10px;
      width: 100%;
      height: 2px;
      transform: scaleX(0);
      opacity: 0;
      transition: transform 0.4s ease-in-out, opacity 0.4s ease-in-out,
        -webkit-transform 0.4s ease-in-out;
    }
    &:hover {
      &:after {
        transform: scaleX(1);
        opacity: 1;
      }
    }
  }
}
```

`_mixins.scss`
$mqs: (
  sm: 30em,
  lg: 64em
) !default;

@mixin mq($mq) {
  @if $mq == ns {

    @media screen and (min-width: #{map-get($mqs, sm)}) {
      @content;
    }

  } @if $mq == m {

      @media screen and (min-width: #{map-get($mqs, sm)}) and (max-width: #{map-get($mqs, lg)}) {
        @content;
      }

    } @if $mq == l {

      @media screen and (min-width: #{map-get($mqs, lg)}) {
        @content;
      }

    }
}

%mwc {
  margin-left: auto;
  margin-right: auto;
  max-width: 100%;
}

@each $size, $width in $mqs {
  %mwc {
    @if $size == sm {
      @media screen and (min-width: #{map-get($mqs, sm)}) {
        margin-left: auto;
        margin-right: auto;
        max-width: 55em;
      }
    }
    @if $size == lg {
      @media screen and (min-width: #{map-get($mqs, lg)}) {
        margin-left: auto;
        margin-right: auto;
        max-width: 72em;
      }
    } @else {
      @media screen and (min-width: #{map-get($mqs, sm)}) and (max-width: #{map-get($mqs, lg)}) {
        margin-left: auto;
        margin-right: auto;
        max-width: 65em;
      }
    }
  }
}
````
